### ISSUE TITLE
cassandra db image

### ISSUE THREAD

**Issue by shahmanash** [mskyttner/ala-docker#2]
the ddb container from cassandra db image seem to lack the occ keyspace (schema created during building of image) when started from make up (docker-compose up). 
However creating container from the per-built image using docker exec -it has the schema.

**Comment by mskyttner** [comment]
"If any build steps change the data within the volume after it has been declared, those changes will be discarded." says https://docs.docker.com/engine/reference/builder/#/volume

I will move the VOLUME statement in #4 and add a test...

**Comment by mskyttner** [comment]
Fixed in #4
